/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRouteImport } from './routes/book'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as LifestyleDisordersRouteImport } from './routes/lifestyle-disorders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCollectionCentersRouteImport } from './routes/admin.collection-centers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminPhlebotomistsRouteImport } from './routes/admin.phlebotomists'
import { Route as BookingOrderIdRouteImport } from './routes/booking.$orderId'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleDisordersRoute = LifestyleDisordersRouteImport.update({
  id: '/lifestyle-disorders',
  path: '/lifestyle-disorders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionCentersRoute = AdminCollectionCentersRouteImport.update({
  id: '/admin/collection-centers',
  path: '/admin/collection-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhlebotomistsRoute = AdminPhlebotomistsRouteImport.update({
  id: '/admin/phlebotomists',
  path: '/admin/phlebotomists',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingOrderIdRoute = BookingOrderIdRouteImport.update({
  id: '/booking/$orderId',
  path: '/booking/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/lifestyle-disorders': typeof LifestyleDisordersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collection-centers': typeof AdminCollectionCentersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/phlebotomists': typeof AdminPhlebotomistsRoute
  '/booking/$orderId': typeof BookingOrderIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/lifestyle-disorders': typeof LifestyleDisordersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collection-centers': typeof AdminCollectionCentersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/phlebotomists': typeof AdminPhlebotomistsRoute
  '/booking/$orderId': typeof BookingOrderIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/lifestyle-disorders': typeof LifestyleDisordersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collection-centers': typeof AdminCollectionCentersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/phlebotomists': typeof AdminPhlebotomistsRoute
  '/booking/$orderId': typeof BookingOrderIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/franchise'
    | '/lifestyle-disorders'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/collection-centers'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/patients'
    | '/admin/phlebotomists'
    | '/booking/$orderId'
    | '/packages/$slug'
    | '/tests/$slug'
    | '/admin/'
    | '/packages/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/franchise'
    | '/lifestyle-disorders'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/collection-centers'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/patients'
    | '/admin/phlebotomists'
    | '/booking/$orderId'
    | '/packages/$slug'
    | '/tests/$slug'
    | '/admin'
    | '/packages'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/franchise'
    | '/lifestyle-disorders'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/collection-centers'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/patients'
    | '/admin/phlebotomists'
    | '/booking/$orderId'
    | '/packages/$slug'
    | '/tests/$slug'
    | '/admin/'
    | '/packages/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FranchiseRoute: typeof FranchiseRoute
  LifestyleDisordersRoute: typeof LifestyleDisordersRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCollectionCentersRoute: typeof AdminCollectionCentersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPhlebotomistsRoute: typeof AdminPhlebotomistsRoute
  BookingOrderIdRoute: typeof BookingOrderIdRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  TestsSlugRoute: typeof TestsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle-disorders': {
      id: '/lifestyle-disorders'
      path: '/lifestyle-disorders'
      fullPath: '/lifestyle-disorders'
      preLoaderRoute: typeof LifestyleDisordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection-centers': {
      id: '/admin/collection-centers'
      path: '/admin/collection-centers'
      fullPath: '/admin/collection-centers'
      preLoaderRoute: typeof AdminCollectionCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/phlebotomists': {
      id: '/admin/phlebotomists'
      path: '/admin/phlebotomists'
      fullPath: '/admin/phlebotomists'
      preLoaderRoute: typeof AdminPhlebotomistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$orderId': {
      id: '/booking/$orderId'
      path: '/booking/$orderId'
      fullPath: '/booking/$orderId'
      preLoaderRoute: typeof BookingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FranchiseRoute: FranchiseRoute,
  LifestyleDisordersRoute: LifestyleDisordersRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCollectionCentersRoute: AdminCollectionCentersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPhlebotomistsRoute: AdminPhlebotomistsRoute,
  BookingOrderIdRoute: BookingOrderIdRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  TestsSlugRoute: TestsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
